version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Start build"
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**

