version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean build -x test

  post_build:
    commands:
      - rm -rf bundle
      - mkdir -p bundle
      - cp appspec.yml bundle/
      - cp -r scripts bundle/
      - cp build/libs/*.jar bundle/
      - chmod -R +x bundle/scripts || true
      - echo "=== bundle tree ==="
      - ls -al bundle
      - ls -al bundle/scripts
      - ls -al bundle/*.jar

artifacts:
  base-directory: bundle
  files:
    - '**/*'
