version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - ls -al
      - chmod +x ./gradlew
      - ./gradlew --version

  build:
    commands:
      - ./gradlew clean build
      - mkdir -p bundle/scripts
      - cp appspec.yml bundle/
      - cp -r scripts bundle/
      - cp build/libs/*.jar bundle/
      - chmod -R +x bundle/scripts || true

artifacts:
  files:
    - bundle/**/*
